"use client";

type Cell = string | number | null | undefined;

function escapeCell(value: Cell) {
  const s = value === null || value === undefined ? "" : String(value);
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

const stamp = () => new Date().toISOString().slice(0, 10);

export function downloadCsv(name: string, headers: string[], rows: Cell[][]) {
  const lines = [
    headers.map(escapeCell).join(","),
    ...rows.map((r) => r.map(escapeCell).join(",")),
  ];
  // BOM keeps ₹ and other non-ASCII characters intact when opened in Excel.
  const blob = new Blob(["﻿" + lines.join("\r\n")], {
    type: "text/csv;charset=utf-8;",
  });
  triggerDownload(blob, `${name}-${stamp()}.csv`);
}

/** Generic tabular PDF used by the reports module. */
export async function downloadTablePdf(options: {
  filename: string;
  title: string;
  subtitle?: string;
  businessName: string;
  headers: string[];
  rows: Cell[][];
  summary?: [string, string][];
}) {
  const { default: JsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new JsPDF({ orientation: "portrait", unit: "pt", format: "a4" });
  const margin = 40;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(15, 23, 42);
  doc.text(options.title, margin, 54);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(options.businessName, margin, 72);
  if (options.subtitle) doc.text(options.subtitle, margin, 87);
  doc.text(
    `Generated ${new Date().toLocaleString("en-IN")}`,
    doc.internal.pageSize.getWidth() - margin,
    72,
    { align: "right" },
  );

  let cursor = options.subtitle ? 108 : 96;

  if (options.summary?.length) {
    autoTable(doc, {
      startY: cursor,
      body: options.summary.map(([k, v]) => [k, v]),
      theme: "plain",
      styles: { fontSize: 10, cellPadding: 4, textColor: [51, 65, 85] },
      columnStyles: {
        0: { fontStyle: "bold", cellWidth: 180, textColor: [100, 116, 139] },
        1: { halign: "left" },
      },
      margin: { left: margin, right: margin },
    });
    cursor = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 18;
  }

  autoTable(doc, {
    startY: cursor,
    head: [options.headers],
    body: options.rows.map((r) => r.map((c) => (c ?? "").toString())),
    styles: { fontSize: 9, cellPadding: 6, textColor: [30, 41, 59] },
    headStyles: {
      fillColor: [241, 245, 249],
      textColor: [71, 85, 105],
      fontStyle: "bold",
    },
    alternateRowStyles: { fillColor: [250, 250, 252] },
    margin: { left: margin, right: margin },
  });

  const pages = doc.getNumberOfPages();
  for (let p = 1; p <= pages; p++) {
    doc.setPage(p);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(
      `Page ${p} of ${pages} · Generated by BizFlow`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 24,
      { align: "center" },
    );
  }

  doc.save(`${options.filename}-${stamp()}.pdf`);
}
